# Generated by Django 3.2.7 on 2021-12-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_auto_20211222_0317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('name',), 'verbose_name': 'Пакет', 'verbose_name_plural': 'Пакет'},
        ),
    ]
