# Generated by Django 3.2.7 on 2021-12-21 21:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterclass', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Clas',
        ),
        migrations.RenameModel(
            old_name='Themes',
            new_name='Theme',
        ),
    ]
