# Generated by Django 3.2.7 on 2021-12-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0003_alter_clas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clas',
            options={'ordering': ('-created',), 'verbose_name': 'Мастер Класс', 'verbose_name_plural': 'Мастер Класс'},
        ),
    ]
