# Generated by Django 3.2.7 on 2021-12-21 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterclass', '0005_alter_clas_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clas',
            name='image',
            field=models.FileField(upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='clas',
            name='overview',
            field=models.TextField(verbose_name='Обзор'),
        ),
        migrations.AlterField(
            model_name='clas',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_created', to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='clas',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Слог'),
        ),
        migrations.AlterField(
            model_name='clas',
            name='themes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='masterclass.theme', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='clas',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='clas',
            name='video',
            field=models.URLField(verbose_name='Видео'),
        ),
    ]
