# Generated by Django 3.2.7 on 2021-12-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0006_auto_20211222_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ('title',), 'verbose_name': 'Тема', 'verbose_name_plural': 'Тема'},
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
