# Generated by Django 3.2.7 on 2021-12-26 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Заголовок')),
                ('video', models.URLField(verbose_name='Видео')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_created', to=settings.AUTH_USER_MODEL, verbose_name='Куратор')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.adventure')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EventTicketSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_sellable_tickets', models.IntegerField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.date')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.event')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.ticket_class')),
            ],
        ),
    ]
