# Generated by Django 3.2.7 on 2021-12-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adventure',
            options={'verbose_name': 'Путешестивие', 'verbose_name_plural': 'Путешестивие'},
        ),
        migrations.AlterModelOptions(
            name='date',
            options={'verbose_name': 'Старт', 'verbose_name_plural': 'Старт'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятие'},
        ),
        migrations.AlterModelOptions(
            name='eventticketsell',
            options={'verbose_name': 'Продажа билетов на мероприятие', 'verbose_name_plural': 'Продажа билетов на мероприятие'},
        ),
        migrations.AlterModelOptions(
            name='ticket_class',
            options={'verbose_name': 'Билеты', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.AddField(
            model_name='eventticketsell',
            name='payment',
            field=models.URLField(null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
